[build]
  # Comando de build
  command = "npm run build"
  
  # Diretório dos arquivos estáticos gerados
  publish = "out"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "20.11.1"
  # Instalar dependências antes do build
  NPM_FLAGS = "--production=false"

# Configurações para pages com trailing slash
[[redirects]]
  from = "/notes/:year/:month/:slug"
  to = "/notes/:year/:month/:slug/"
  status = 301

[[redirects]]
  from = "/post/:slug"
  to = "/post/:slug/"
  status = 301

# Headers para melhor performance
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
